name: Sync IPv6 M3U File

on:
  schedule:
    # 每天凌晨2点运行一次
    - cron: '0 2 * * *'

  workflow_dispatch: # 允许手动触发

jobs:

  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 0

  sync:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出当前仓库代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: 创建目录并下载文件
    - name: Download m3u file to IPV6 directory
      run: |
        mkdir -p IPV6
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O IPV6/ipv6.m3u

      # Step 3: 检查文件是否修改
    - name: Check for changes
      id: check_changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add IPV6/ipv6.m3u
        if ! git diff --cached --quiet; then
          echo "modified=true" >> $GITHUB_ENV
        else
          echo "modified=false" >> $GITHUB_ENV
        fi

      # Step 4: 提交到当前仓库（仅在文件修改时）
    - name: Commit and push changes
      if: env.modified == 'true'
      run: |
        git commit -m "Update ipv6.m3u"
        git push        

